# Backup configuration file

# Backup path, default path is recommended
BACKUP_PATH="/etc/backup.borg"

# Backup disk PTUUID
PTUUID="ptuuid"

# Backup partition UUID
UUID="uuid"

# Disk partition mountpoint, DON'T write "/" at the end
MOUNTPOINT="path/to/mountpoint"

# Borg repository passphrase
export $BORG_PASSPHRASE="passphrase"
